name: Build & Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.actor }}/virtualletters-api:latest -f VirtualLetters.Api/Dockerfile 

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.actor }}/virtualletters-api:latest
